import Head from 'next/head'
import Image from 'next/image'
import { Fragment, useState } from 'react'
import { Button, Card } from 'react-bootstrap'
import { CreateItemModal } from '../src/create-item-modal'
import { Items } from '../src/items'
import styles from '../styles/Home.module.css'

export default function Home() {
	const [creating, setCreating] = useState(false)

	return (
		<Fragment>
			<Head>
				<title>Invertarify</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<Button onClick={() => {
					setCreating(true)
				}}>
					Create item
        	</Button>
			</div>

			<Items />

			<CreateItemModal
				show={creating}
				onSuccess={() => {

				}}
				onCancel={() => {
					setCreating(false)
				}} />
		</Fragment>
	)
}
