import Head from 'next/head'
import Image from 'next/image'
import { Fragment, useState } from 'react'
import { Button, Card, Container } from 'react-bootstrap'
import { ContainerList } from '../src/container/container-list'
import { CreateItemModal } from '../src/create-item-modal'
import { ItemsList } from '../src/item/items-list'
import { Items } from '../src/items'
import { NavigationBar } from '../src/navigationbar'
import styles from '../styles/Home.module.css'

export default function Home() {
	const [creating, setCreating] = useState(false)

	return (
		<Fragment>
			<Head>
				<title>Invertarify</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Fragment>
				<NavigationBar />
			</Fragment>
			<Container>
				<div>
					<Button onClick={() => {
						setCreating(true)
					}}>
						Create item
					</Button>
				</div>
				<ItemsList />

				<CreateItemModal
					show={creating}
					onSuccess={() => {
						setCreating(false)
					}}
					onCancel={() => {
						setCreating(false)
					}} />

				<ContainerList />
			</Container>
		</Fragment>
	)
}
