import Head from 'next/head'
import Image from 'next/image'
import { Fragment, useState } from 'react'
import { Button, Card, Col, Container, FormControl, Row } from 'react-bootstrap'
import { ContainerList } from '../src/container/container-list'
import { RootNode } from '../src/nodes/root-node'
import { CreateContainerForm } from '../src/container/create-container-modal'
import { CreateItemModal } from '../src/create-item-modal'
import { ItemsList } from '../src/item/items-list'
import { Items } from '../src/items'
import { NavigationBar } from '../src/navigationbar'
import styles from '../styles/Home.module.css'
import { MainContent } from '../src/main-content/main-content'

export default function Home() {
	const [creating, setCreating] = useState(false)
	const [con, setCon] = useState(false)

	return (
		<Fragment>
			<Head>
				<title>Invertarify</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Fragment>
				<NavigationBar />
			</Fragment>
			<Container fluid={true}>
				<Row>
					<Col sm={2}>
						<div style={{
							marginBottom: "10px"
						}}>
							<Button onClick={() => {
								setCreating(true)
							}}>
								Create item
							</Button>
						</div>
						<div>
							<Button onClick={() => {
								setCon(true)
							}}>
								Create container
							</Button>
						</div>
					</Col>
					<Col>
						<MainContent />
					</Col>
				</Row>
			</Container>

			<CreateItemModal
				show={creating}
				onSuccess={() => {
					setCreating(false)
				}}
				onCancel={() => {
					setCreating(false)
				}} />

			<CreateContainerForm
				show={con}
				onHide={() => {
					setCon(false)
				}}/>
		</Fragment>
	)
}
