
mutation updateItem($input: UpdateItem!) {
	updateItem(input: $input) {
		item {
			id
			name
			metadata
		}
	}
}

mutation createContainer($input: CreateContainer!) {
	createContainer(input: $input) {
		container {
			id
			name
		}
	}
}

mutation updateContainer($input: UpdateContainer!) {
	updateContainer(input: $input) {
		container {
			id
			name
		}
	}
}

mutation placeItemToContainer($input: PlaceItemToContainer!) {
	placeItemToContainer(input: $input) {
		container {
			id
			name
		}
		item {
			id
			name
		}
		previousContainer {
			id
			name
		}
	}
}

mutation placeContainerToContainer($input: PlaceContainerToContainer!) {
	placeContainerToContainer(input: $input) {
		srcContainer {
			id
			name
		}
		dstContainer {
			id
			name
		}
		previousContainer {
			id
			name
		}
	}
}

mutation archiveItem($input: ArchiveItem!) {
	archiveItem(input: $input) {
		item {
			id
			name
			deletedAt
		}
	}
}

mutation archiveContainer($input: ArchiveContainer!) {
	archiveContainer(input: $input) {
		container {
			id
			name
			deletedAt
		}
	}
}

mutation addPictureForItem($input: AddPictureForItem!) {
	addPictureForItem(input: $input) {
		item {
			id
			name
		}
	}
}