name: Build
on: [push]
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/server
          tags: jaska/invertarify/server
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: docker build -f ${{ github.workspace }}/web/dockerfile -t jaska/invertarify/web ${{ github.workspace }}/web