name: Buildd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -f ${{ github.workspace }}/server/dockerfile -t jaska/invertarify/server ${{ github.workspace }}/server