name: Build
on: [push]
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tag_with_ref: true
          context: ${{ github.workspace }}/server
          tags: jaska/invertarify/server
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tag_with_ref: true
          context: ${{ github.workspace }}/web
          tags: jaska/invertarify/web