name: Buildd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: docker build -f ${{ github.workspace }}/server/dockerfile -t jaska/invertarify/server ${{ github.workspace }}/server